name: CI

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Clone audio file repo
        run: git clone https://${AUDIO_KEY}:x-oauth-basic@github.com/panmau/stormsimulator-files.git
        env: 
          AUDIO_KEY: ${{ secrets.AUDIO_KEY }}
          AUDIO_URL: ${{ secrets.AUDIO_URL }}

      - name: Prepare Distribution Folder
        run: |
          tree
          mv ${REPO_NAME}/audio audio
          rm -r ${REPO_NAME}
          rsync -a * dist/
        env:
          REPO_NAME: ${{ secrets.AUDIO_REPO }}

      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist -m '${{ github.head_ref }}'

      - name: Deploy Release @next
        if: github.ref == 'refs/heads/next'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist -b next

      - name: Deploy Release
        if: github.ref == 'refs/heads/main'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
